<?php

declare(strict_types=1);

return [
    'signIn.start.title' => 'Bei {applicationName} anmelden',
    'signIn.start.subtitle' => 'Willkommen zurück! Melde dich an, um fortzufahren.',
    'signIn.start.actionText' => 'Noch kein Konto?',
    'signIn.start.actionLink' => 'Konto erstellen',
    'signIn.password.title' => 'Passwort eingeben',
    'signIn.password.subtitle' => 'Gib das Passwort deines Kontos ein.',
    'signIn.password.actionLink' => 'Passwort vergessen?',
    'signIn.emailCode.title' => 'E-Mail prüfen',
    'signIn.emailCode.subtitle' => 'Wir haben einen Code an {identifier} gesendet. Gib ihn unten ein.',
    'signIn.emailCode.resendButton' => 'Code erneut senden',
    'signIn.emailLink.title' => 'E-Mail prüfen',
    'signIn.emailLink.subtitle' => 'Klicke auf den Link, den wir an {identifier} gesendet haben.',
    'signIn.phoneCode.title' => 'Telefon prüfen',
    'signIn.phoneCode.subtitle' => 'Wir haben einen Code an {identifier} gesendet.',
    'signIn.totp.title' => 'Zwei-Faktor-Verifizierung',
    'signIn.totp.subtitle' => 'Gib den Code aus deiner Authenticator-App ein.',
    'signIn.backupCode.title' => 'Backup-Code verwenden',
    'signIn.backupCode.subtitle' => 'Gib einen der Backup-Codes ein, die du beim Aktivieren der Zwei-Faktor-Verifizierung gespeichert hast.',
    'signIn.forgotPassword.title' => 'Passwort vergessen?',
    'signIn.forgotPassword.subtitle' => 'Gib deine E-Mail ein – wir senden dir einen Code zum Zurücksetzen.',
    'signIn.resetPassword.title' => 'Passwort zurücksetzen',
    'signIn.resetPassword.subtitle' => 'Wähle ein neues Passwort für dein Konto.',
    'signIn.alternativeMethods.title' => 'Andere Methode verwenden',
    'signIn.alternativeMethods.subtitle' => 'Wähle, wie du dich anmeldest.',

    'signUp.start.title' => 'Erstelle dein {applicationName}-Konto',
    'signUp.start.subtitle' => 'Willkommen! Fülle die Angaben aus, um loszulegen.',
    'signUp.start.actionText' => 'Schon ein Konto?',
    'signUp.start.actionLink' => 'Anmelden',
    'signUp.emailCode.title' => 'E-Mail bestätigen',
    'signUp.emailCode.subtitle' => 'Gib den Bestätigungscode ein, den wir an {identifier} gesendet haben.',
    'signUp.phoneCode.title' => 'Telefon bestätigen',
    'signUp.phoneCode.subtitle' => 'Gib den Bestätigungscode ein, den wir an {identifier} gesendet haben.',
    'signUp.continue.title' => 'Fehlende Felder ausfüllen',
    'signUp.continue.subtitle' => 'Noch ein paar Angaben und du bist drin.',

    'userProfile.start.headerTitle' => 'Konto',
    'userProfile.start.headerSubtitle' => 'Verwalte deine Kontoinformationen.',
    'userProfile.start.profileSection.title' => 'Profil',
    'userProfile.start.emailAddressesSection.title' => 'E-Mail-Adressen',
    'userProfile.start.phoneNumbersSection.title' => 'Telefonnummern',
    'userProfile.start.passkeysSection.title' => 'Passkeys',
    'userProfile.start.connectedAccountsSection.title' => 'Verbundene Konten',
    'userProfile.start.passwordSection.title' => 'Passwort',
    'userProfile.start.mfaSection.title' => 'Zwei-Faktor-Verifizierung',
    'userProfile.start.activeDevicesSection.title' => 'Aktive Geräte',
    'userProfile.start.dangerSection.title' => 'Gefahrenzone',
    'userProfile.start.dangerSection.deleteAccountButton' => 'Konto löschen',

    'userButton.action__manageAccount' => 'Konto verwalten',
    'userButton.action__signOut' => 'Abmelden',
    'userButton.action__signOutAll' => 'Von allen Konten abmelden',
    'userButton.action__addAccount' => 'Konto hinzufügen',

    'organizationProfile.start.headerTitle' => 'Organisation',
    'organizationProfile.start.headerSubtitle' => 'Verwalte die Einstellungen deiner Organisation.',
    'organizationProfile.membersPage.title' => 'Mitglieder',
    'organizationProfile.invitationsPage.title' => 'Einladungen',
    'organizationProfile.dangerSection.leaveOrganizationButton' => 'Organisation verlassen',
    'organizationProfile.dangerSection.deleteOrganizationButton' => 'Organisation löschen',

    'organizationSwitcher.action__createOrganization' => 'Organisation erstellen',
    'organizationSwitcher.action__manageOrganization' => 'Organisation verwalten',
    'organizationSwitcher.personalWorkspace' => 'Persönliches Konto',
    'organizationSwitcher.notSelected' => 'Organisation auswählen',

    'organizationList.title' => 'Wähle eine Organisation',
    'organizationList.subtitle' => 'Wähle aus, mit welcher Organisation du fortfährst.',
    'organizationList.createOrganization' => 'Organisation erstellen',

    'createOrganization.title' => 'Organisation erstellen',
    'createOrganization.formButtonSubmit' => 'Organisation erstellen',

    'formFieldLabel__emailAddress' => 'E-Mail-Adresse',
    'formFieldLabel__phoneNumber' => 'Telefonnummer',
    'formFieldLabel__password' => 'Passwort',
    'formFieldLabel__confirmPassword' => 'Passwort bestätigen',
    'formFieldLabel__currentPassword' => 'Aktuelles Passwort',
    'formFieldLabel__newPassword' => 'Neues Passwort',
    'formFieldLabel__firstName' => 'Vorname',
    'formFieldLabel__lastName' => 'Nachname',
    'formFieldLabel__username' => 'Benutzername',
    'formFieldLabel__code' => 'Code',
    'formFieldLabel__backupCode' => 'Backup-Code',
    'formFieldLabel__organizationName' => 'Name der Organisation',
    'formFieldLabel__organizationSlug' => 'Kennung',
    'formFieldHint__optional' => 'Optional',
    'formFieldHint__passwordStrength' => 'Verwende mindestens 8 Zeichen mit Buchstaben und Zahlen.',
    'formFieldError__notMatchingPasswords' => 'Die Passwörter stimmen nicht überein.',
    'formFieldError__weakPassword' => 'Das Passwort ist zu schwach.',
    'formFieldError__invalidCode' => 'Ungültiger Code.',
    'formFieldAction__forgotPassword' => 'Passwort vergessen?',
    'formFieldAction__resendCode' => 'Code erneut senden',
    'formFieldAction__showPassword' => 'Passwort anzeigen',
    'formFieldAction__hidePassword' => 'Passwort verbergen',
    'formFieldInputPlaceholder__emailAddress' => 'name@beispiel.de',
    'formFieldInputPlaceholder__phoneNumber' => '+49 30 12345678',
    'formFieldInputPlaceholder__code' => '000000',
    'formButtonPrimary' => 'Weiter',
    'formButtonReset' => 'Abbrechen',
    'socialButtonsBlockButton' => 'Weiter mit {provider}',
    'dividerText' => 'oder',
    'footerActionLink__signIn' => 'Anmelden',
    'footerActionLink__signUp' => 'Konto erstellen',
    'footerActionLink__useAnotherMethod' => 'Andere Methode verwenden',
    'badge__primary' => 'Primär',
    'badge__verified' => 'Verifiziert',
    'badge__unverified' => 'Nicht verifiziert',
    'badge__default' => 'Standard',
    'badge__you' => 'Du',
    'paginationButton__previous' => 'Zurück',
    'paginationButton__next' => 'Weiter',
    'paginationRowText__displaying' => '{start}-{end} von {total}',
    'paginationRowText__of' => 'von',
];
