<?php

declare(strict_types=1);

return [
    'signIn.start.title' => 'Inicia sesión en {applicationName}',
    'signIn.start.subtitle' => '¡Bienvenido de nuevo! Inicia sesión para continuar.',
    'signIn.start.actionText' => '¿No tienes cuenta?',
    'signIn.start.actionLink' => 'Crear cuenta',
    'signIn.password.title' => 'Introduce tu contraseña',
    'signIn.password.subtitle' => 'Introduce la contraseña asociada a tu cuenta.',
    'signIn.password.actionLink' => '¿Olvidaste tu contraseña?',
    'signIn.emailCode.title' => 'Revisa tu correo',
    'signIn.emailCode.subtitle' => 'Hemos enviado un código a {identifier}. Introdúcelo aquí.',
    'signIn.emailCode.resendButton' => 'Reenviar código',
    'signIn.emailLink.title' => 'Revisa tu correo',
    'signIn.emailLink.subtitle' => 'Haz clic en el enlace que enviamos a {identifier} para continuar.',
    'signIn.phoneCode.title' => 'Revisa tu teléfono',
    'signIn.phoneCode.subtitle' => 'Hemos enviado un código a {identifier}.',
    'signIn.totp.title' => 'Verificación en dos pasos',
    'signIn.totp.subtitle' => 'Introduce el código de tu aplicación de autenticación.',
    'signIn.backupCode.title' => 'Usar un código de respaldo',
    'signIn.backupCode.subtitle' => 'Introduce uno de los códigos de respaldo guardados al activar la verificación en dos pasos.',
    'signIn.forgotPassword.title' => '¿Olvidaste tu contraseña?',
    'signIn.forgotPassword.subtitle' => 'Introduce tu correo y te enviaremos un código para restablecerla.',
    'signIn.resetPassword.title' => 'Restablecer contraseña',
    'signIn.resetPassword.subtitle' => 'Elige una nueva contraseña para tu cuenta.',
    'signIn.alternativeMethods.title' => 'Usar otro método',
    'signIn.alternativeMethods.subtitle' => 'Elige cómo iniciar sesión.',

    'signUp.start.title' => 'Crea tu cuenta en {applicationName}',
    'signUp.start.subtitle' => '¡Bienvenido! Completa los datos para empezar.',
    'signUp.start.actionText' => '¿Ya tienes cuenta?',
    'signUp.start.actionLink' => 'Iniciar sesión',
    'signUp.emailCode.title' => 'Verifica tu correo',
    'signUp.emailCode.subtitle' => 'Introduce el código de verificación que enviamos a {identifier}.',
    'signUp.phoneCode.title' => 'Verifica tu teléfono',
    'signUp.phoneCode.subtitle' => 'Introduce el código de verificación que enviamos a {identifier}.',
    'signUp.continue.title' => 'Completa los campos restantes',
    'signUp.continue.subtitle' => 'Unos detalles más y listo.',

    'userProfile.start.headerTitle' => 'Cuenta',
    'userProfile.start.headerSubtitle' => 'Gestiona la información de tu cuenta.',
    'userProfile.start.profileSection.title' => 'Perfil',
    'userProfile.start.emailAddressesSection.title' => 'Correos electrónicos',
    'userProfile.start.phoneNumbersSection.title' => 'Teléfonos',
    'userProfile.start.passkeysSection.title' => 'Llaves de acceso',
    'userProfile.start.connectedAccountsSection.title' => 'Cuentas conectadas',
    'userProfile.start.passwordSection.title' => 'Contraseña',
    'userProfile.start.mfaSection.title' => 'Verificación en dos pasos',
    'userProfile.start.activeDevicesSection.title' => 'Dispositivos activos',
    'userProfile.start.dangerSection.title' => 'Zona de peligro',
    'userProfile.start.dangerSection.deleteAccountButton' => 'Eliminar cuenta',

    'userButton.action__manageAccount' => 'Gestionar cuenta',
    'userButton.action__signOut' => 'Cerrar sesión',
    'userButton.action__signOutAll' => 'Cerrar sesión en todas las cuentas',
    'userButton.action__addAccount' => 'Añadir cuenta',

    'organizationProfile.start.headerTitle' => 'Organización',
    'organizationProfile.start.headerSubtitle' => 'Gestiona la configuración de tu organización.',
    'organizationProfile.membersPage.title' => 'Miembros',
    'organizationProfile.invitationsPage.title' => 'Invitaciones',
    'organizationProfile.dangerSection.leaveOrganizationButton' => 'Salir de la organización',
    'organizationProfile.dangerSection.deleteOrganizationButton' => 'Eliminar organización',

    'organizationSwitcher.action__createOrganization' => 'Crear organización',
    'organizationSwitcher.action__manageOrganization' => 'Gestionar organización',
    'organizationSwitcher.personalWorkspace' => 'Cuenta personal',
    'organizationSwitcher.notSelected' => 'Seleccionar organización',

    'organizationList.title' => 'Elige una organización',
    'organizationList.subtitle' => 'Selecciona con qué organización continuar.',
    'organizationList.createOrganization' => 'Crear organización',

    'createOrganization.title' => 'Crear organización',
    'createOrganization.formButtonSubmit' => 'Crear organización',

    'formFieldLabel__emailAddress' => 'Correo electrónico',
    'formFieldLabel__phoneNumber' => 'Teléfono',
    'formFieldLabel__password' => 'Contraseña',
    'formFieldLabel__confirmPassword' => 'Confirmar contraseña',
    'formFieldLabel__currentPassword' => 'Contraseña actual',
    'formFieldLabel__newPassword' => 'Nueva contraseña',
    'formFieldLabel__firstName' => 'Nombre',
    'formFieldLabel__lastName' => 'Apellido',
    'formFieldLabel__username' => 'Nombre de usuario',
    'formFieldLabel__code' => 'Código',
    'formFieldLabel__backupCode' => 'Código de respaldo',
    'formFieldLabel__organizationName' => 'Nombre de la organización',
    'formFieldLabel__organizationSlug' => 'Identificador',
    'formFieldHint__optional' => 'Opcional',
    'formFieldHint__passwordStrength' => 'Usa 8 o más caracteres con letras y números.',
    'formFieldError__notMatchingPasswords' => 'Las contraseñas no coinciden.',
    'formFieldError__weakPassword' => 'La contraseña es demasiado débil.',
    'formFieldError__invalidCode' => 'Código no válido.',
    'formFieldAction__forgotPassword' => '¿Olvidaste tu contraseña?',
    'formFieldAction__resendCode' => 'Reenviar código',
    'formFieldAction__showPassword' => 'Mostrar contraseña',
    'formFieldAction__hidePassword' => 'Ocultar contraseña',
    'formFieldInputPlaceholder__emailAddress' => 'nombre@ejemplo.com',
    'formFieldInputPlaceholder__phoneNumber' => '+34 600 000 000',
    'formFieldInputPlaceholder__code' => '000000',
    'formButtonPrimary' => 'Continuar',
    'formButtonReset' => 'Cancelar',
    'socialButtonsBlockButton' => 'Continuar con {provider}',
    'dividerText' => 'o',
    'footerActionLink__signIn' => 'Iniciar sesión',
    'footerActionLink__signUp' => 'Crear cuenta',
    'footerActionLink__useAnotherMethod' => 'Usar otro método',
    'badge__primary' => 'Principal',
    'badge__verified' => 'Verificado',
    'badge__unverified' => 'Sin verificar',
    'badge__default' => 'Predeterminado',
    'badge__you' => 'Tú',
    'paginationButton__previous' => 'Anterior',
    'paginationButton__next' => 'Siguiente',
    'paginationRowText__displaying' => 'Mostrando {start}-{end} de {total}',
    'paginationRowText__of' => 'de',
];
