<?php

declare(strict_types=1);

return [
    'signIn.start.title' => 'Se connecter à {applicationName}',
    'signIn.start.subtitle' => 'Heureux de vous revoir ! Connectez-vous pour continuer.',
    'signIn.start.actionText' => 'Pas encore inscrit ?',
    'signIn.start.actionLink' => 'Créer un compte',
    'signIn.password.title' => 'Saisissez votre mot de passe',
    'signIn.password.subtitle' => 'Saisissez le mot de passe associé à votre compte.',
    'signIn.password.actionLink' => 'Mot de passe oublié ?',
    'signIn.emailCode.title' => 'Consultez votre boîte mail',
    'signIn.emailCode.subtitle' => 'Nous avons envoyé un code à {identifier}. Saisissez-le ci-dessous.',
    'signIn.emailCode.resendButton' => 'Renvoyer le code',
    'signIn.emailLink.title' => 'Consultez votre boîte mail',
    'signIn.emailLink.subtitle' => 'Cliquez sur le lien envoyé à {identifier} pour continuer.',
    'signIn.phoneCode.title' => 'Consultez vos SMS',
    'signIn.phoneCode.subtitle' => 'Nous avons envoyé un code à {identifier}.',
    'signIn.totp.title' => 'Vérification en deux étapes',
    'signIn.totp.subtitle' => 'Saisissez le code de votre application d\'authentification.',
    'signIn.backupCode.title' => 'Utiliser un code de secours',
    'signIn.backupCode.subtitle' => 'Saisissez l\'un des codes de secours enregistrés lors de l\'activation de la vérification en deux étapes.',
    'signIn.forgotPassword.title' => 'Mot de passe oublié ?',
    'signIn.forgotPassword.subtitle' => 'Saisissez votre e-mail et nous enverrons un code de réinitialisation.',
    'signIn.resetPassword.title' => 'Réinitialiser le mot de passe',
    'signIn.resetPassword.subtitle' => 'Choisissez un nouveau mot de passe pour votre compte.',
    'signIn.alternativeMethods.title' => 'Utiliser une autre méthode',
    'signIn.alternativeMethods.subtitle' => 'Choisissez comment vous connecter.',

    'signUp.start.title' => 'Créez votre compte {applicationName}',
    'signUp.start.subtitle' => 'Bienvenue ! Remplissez les informations pour démarrer.',
    'signUp.start.actionText' => 'Vous avez déjà un compte ?',
    'signUp.start.actionLink' => 'Se connecter',
    'signUp.emailCode.title' => 'Vérifiez votre e-mail',
    'signUp.emailCode.subtitle' => 'Saisissez le code de vérification envoyé à {identifier}.',
    'signUp.phoneCode.title' => 'Vérifiez votre téléphone',
    'signUp.phoneCode.subtitle' => 'Saisissez le code de vérification envoyé à {identifier}.',
    'signUp.continue.title' => 'Complétez les champs manquants',
    'signUp.continue.subtitle' => 'Encore quelques détails et c\'est fini.',

    'userProfile.start.headerTitle' => 'Compte',
    'userProfile.start.headerSubtitle' => 'Gérez les informations de votre compte.',
    'userProfile.start.profileSection.title' => 'Profil',
    'userProfile.start.emailAddressesSection.title' => 'Adresses e-mail',
    'userProfile.start.phoneNumbersSection.title' => 'Numéros de téléphone',
    'userProfile.start.passkeysSection.title' => 'Clés d\'accès',
    'userProfile.start.connectedAccountsSection.title' => 'Comptes connectés',
    'userProfile.start.passwordSection.title' => 'Mot de passe',
    'userProfile.start.mfaSection.title' => 'Vérification en deux étapes',
    'userProfile.start.activeDevicesSection.title' => 'Appareils actifs',
    'userProfile.start.dangerSection.title' => 'Zone sensible',
    'userProfile.start.dangerSection.deleteAccountButton' => 'Supprimer le compte',

    'userButton.action__manageAccount' => 'Gérer le compte',
    'userButton.action__signOut' => 'Se déconnecter',
    'userButton.action__signOutAll' => 'Se déconnecter de tous les comptes',
    'userButton.action__addAccount' => 'Ajouter un compte',

    'organizationProfile.start.headerTitle' => 'Organisation',
    'organizationProfile.start.headerSubtitle' => 'Gérez les paramètres de votre organisation.',
    'organizationProfile.membersPage.title' => 'Membres',
    'organizationProfile.invitationsPage.title' => 'Invitations',
    'organizationProfile.dangerSection.leaveOrganizationButton' => 'Quitter l\'organisation',
    'organizationProfile.dangerSection.deleteOrganizationButton' => 'Supprimer l\'organisation',

    'organizationSwitcher.action__createOrganization' => 'Créer une organisation',
    'organizationSwitcher.action__manageOrganization' => 'Gérer l\'organisation',
    'organizationSwitcher.personalWorkspace' => 'Compte personnel',
    'organizationSwitcher.notSelected' => 'Choisir une organisation',

    'organizationList.title' => 'Choisissez une organisation',
    'organizationList.subtitle' => 'Sélectionnez l\'organisation à utiliser.',
    'organizationList.createOrganization' => 'Créer une organisation',

    'createOrganization.title' => 'Créer une organisation',
    'createOrganization.formButtonSubmit' => 'Créer l\'organisation',

    'formFieldLabel__emailAddress' => 'Adresse e-mail',
    'formFieldLabel__phoneNumber' => 'Numéro de téléphone',
    'formFieldLabel__password' => 'Mot de passe',
    'formFieldLabel__confirmPassword' => 'Confirmer le mot de passe',
    'formFieldLabel__currentPassword' => 'Mot de passe actuel',
    'formFieldLabel__newPassword' => 'Nouveau mot de passe',
    'formFieldLabel__firstName' => 'Prénom',
    'formFieldLabel__lastName' => 'Nom',
    'formFieldLabel__username' => 'Nom d\'utilisateur',
    'formFieldLabel__code' => 'Code',
    'formFieldLabel__backupCode' => 'Code de secours',
    'formFieldLabel__organizationName' => 'Nom de l\'organisation',
    'formFieldLabel__organizationSlug' => 'Identifiant',
    'formFieldHint__optional' => 'Facultatif',
    'formFieldHint__passwordStrength' => 'Utilisez au moins 8 caractères avec lettres et chiffres.',
    'formFieldError__notMatchingPasswords' => 'Les mots de passe ne correspondent pas.',
    'formFieldError__weakPassword' => 'Le mot de passe est trop faible.',
    'formFieldError__invalidCode' => 'Code invalide.',
    'formFieldAction__forgotPassword' => 'Mot de passe oublié ?',
    'formFieldAction__resendCode' => 'Renvoyer le code',
    'formFieldAction__showPassword' => 'Afficher le mot de passe',
    'formFieldAction__hidePassword' => 'Masquer le mot de passe',
    'formFieldInputPlaceholder__emailAddress' => 'nom@exemple.com',
    'formFieldInputPlaceholder__phoneNumber' => '+33 6 12 34 56 78',
    'formFieldInputPlaceholder__code' => '000000',
    'formButtonPrimary' => 'Continuer',
    'formButtonReset' => 'Annuler',
    'socialButtonsBlockButton' => 'Continuer avec {provider}',
    'dividerText' => 'ou',
    'footerActionLink__signIn' => 'Se connecter',
    'footerActionLink__signUp' => 'Créer un compte',
    'footerActionLink__useAnotherMethod' => 'Utiliser une autre méthode',
    'badge__primary' => 'Principal',
    'badge__verified' => 'Vérifié',
    'badge__unverified' => 'Non vérifié',
    'badge__default' => 'Par défaut',
    'badge__you' => 'Vous',
    'paginationButton__previous' => 'Précédent',
    'paginationButton__next' => 'Suivant',
    'paginationRowText__displaying' => 'Affichage de {start} à {end} sur {total}',
    'paginationRowText__of' => 'sur',
];
