<?php

declare(strict_types=1);

return [
    'signIn.start.title' => 'Entrar em {applicationName}',
    'signIn.start.subtitle' => 'Bem-vindo de volta! Entre para continuar.',
    'signIn.start.actionText' => 'Não tem conta?',
    'signIn.start.actionLink' => 'Criar conta',
    'signIn.password.title' => 'Digite sua senha',
    'signIn.password.subtitle' => 'Digite a senha associada à sua conta.',
    'signIn.password.actionLink' => 'Esqueceu a senha?',
    'signIn.emailCode.title' => 'Verifique seu e-mail',
    'signIn.emailCode.subtitle' => 'Enviamos um código para {identifier}. Digite-o abaixo.',
    'signIn.emailCode.resendButton' => 'Reenviar código',
    'signIn.emailLink.title' => 'Verifique seu e-mail',
    'signIn.emailLink.subtitle' => 'Clique no link que enviamos para {identifier} para continuar.',
    'signIn.phoneCode.title' => 'Verifique seu telefone',
    'signIn.phoneCode.subtitle' => 'Enviamos um código para {identifier}.',
    'signIn.totp.title' => 'Verificação em duas etapas',
    'signIn.totp.subtitle' => 'Digite o código do seu aplicativo autenticador.',
    'signIn.backupCode.title' => 'Usar um código de backup',
    'signIn.backupCode.subtitle' => 'Digite um dos códigos de backup salvos ao ativar a verificação em duas etapas.',
    'signIn.forgotPassword.title' => 'Esqueceu a senha?',
    'signIn.forgotPassword.subtitle' => 'Digite seu e-mail e enviaremos um código para redefini-la.',
    'signIn.resetPassword.title' => 'Redefinir senha',
    'signIn.resetPassword.subtitle' => 'Escolha uma nova senha para sua conta.',
    'signIn.alternativeMethods.title' => 'Usar outro método',
    'signIn.alternativeMethods.subtitle' => 'Escolha como entrar.',

    'signUp.start.title' => 'Crie sua conta em {applicationName}',
    'signUp.start.subtitle' => 'Boas-vindas! Preencha os dados para começar.',
    'signUp.start.actionText' => 'Já tem uma conta?',
    'signUp.start.actionLink' => 'Entrar',
    'signUp.emailCode.title' => 'Verifique seu e-mail',
    'signUp.emailCode.subtitle' => 'Digite o código de verificação que enviamos para {identifier}.',
    'signUp.phoneCode.title' => 'Verifique seu telefone',
    'signUp.phoneCode.subtitle' => 'Digite o código de verificação que enviamos para {identifier}.',
    'signUp.continue.title' => 'Complete os campos restantes',
    'signUp.continue.subtitle' => 'Mais alguns detalhes e você está dentro.',

    'userProfile.start.headerTitle' => 'Conta',
    'userProfile.start.headerSubtitle' => 'Gerencie as informações da sua conta.',
    'userProfile.start.profileSection.title' => 'Perfil',
    'userProfile.start.emailAddressesSection.title' => 'Endereços de e-mail',
    'userProfile.start.phoneNumbersSection.title' => 'Telefones',
    'userProfile.start.passkeysSection.title' => 'Passkeys',
    'userProfile.start.connectedAccountsSection.title' => 'Contas conectadas',
    'userProfile.start.passwordSection.title' => 'Senha',
    'userProfile.start.mfaSection.title' => 'Verificação em duas etapas',
    'userProfile.start.activeDevicesSection.title' => 'Dispositivos ativos',
    'userProfile.start.dangerSection.title' => 'Zona de perigo',
    'userProfile.start.dangerSection.deleteAccountButton' => 'Excluir conta',

    'userButton.action__manageAccount' => 'Gerenciar conta',
    'userButton.action__signOut' => 'Sair',
    'userButton.action__signOutAll' => 'Sair de todas as contas',
    'userButton.action__addAccount' => 'Adicionar conta',

    'organizationProfile.start.headerTitle' => 'Organização',
    'organizationProfile.start.headerSubtitle' => 'Gerencie as configurações da sua organização.',
    'organizationProfile.membersPage.title' => 'Membros',
    'organizationProfile.invitationsPage.title' => 'Convites',
    'organizationProfile.dangerSection.leaveOrganizationButton' => 'Sair da organização',
    'organizationProfile.dangerSection.deleteOrganizationButton' => 'Excluir organização',

    'organizationSwitcher.action__createOrganization' => 'Criar organização',
    'organizationSwitcher.action__manageOrganization' => 'Gerenciar organização',
    'organizationSwitcher.personalWorkspace' => 'Conta pessoal',
    'organizationSwitcher.notSelected' => 'Selecionar organização',

    'organizationList.title' => 'Escolha uma organização',
    'organizationList.subtitle' => 'Selecione com qual organização continuar.',
    'organizationList.createOrganization' => 'Criar organização',

    'createOrganization.title' => 'Criar organização',
    'createOrganization.formButtonSubmit' => 'Criar organização',

    'formFieldLabel__emailAddress' => 'E-mail',
    'formFieldLabel__phoneNumber' => 'Telefone',
    'formFieldLabel__password' => 'Senha',
    'formFieldLabel__confirmPassword' => 'Confirmar senha',
    'formFieldLabel__currentPassword' => 'Senha atual',
    'formFieldLabel__newPassword' => 'Nova senha',
    'formFieldLabel__firstName' => 'Nome',
    'formFieldLabel__lastName' => 'Sobrenome',
    'formFieldLabel__username' => 'Nome de usuário',
    'formFieldLabel__code' => 'Código',
    'formFieldLabel__backupCode' => 'Código de backup',
    'formFieldLabel__organizationName' => 'Nome da organização',
    'formFieldLabel__organizationSlug' => 'Identificador',
    'formFieldHint__optional' => 'Opcional',
    'formFieldHint__passwordStrength' => 'Use 8 ou mais caracteres com letras e números.',
    'formFieldError__notMatchingPasswords' => 'As senhas não coincidem.',
    'formFieldError__weakPassword' => 'Senha muito fraca.',
    'formFieldError__invalidCode' => 'Código inválido.',
    'formFieldAction__forgotPassword' => 'Esqueceu a senha?',
    'formFieldAction__resendCode' => 'Reenviar código',
    'formFieldAction__showPassword' => 'Mostrar senha',
    'formFieldAction__hidePassword' => 'Ocultar senha',
    'formFieldInputPlaceholder__emailAddress' => 'nome@exemplo.com',
    'formFieldInputPlaceholder__phoneNumber' => '+55 11 99999 9999',
    'formFieldInputPlaceholder__code' => '000000',
    'formButtonPrimary' => 'Continuar',
    'formButtonReset' => 'Cancelar',
    'socialButtonsBlockButton' => 'Continuar com {provider}',
    'dividerText' => 'ou',
    'footerActionLink__signIn' => 'Entrar',
    'footerActionLink__signUp' => 'Criar conta',
    'footerActionLink__useAnotherMethod' => 'Usar outro método',
    'badge__primary' => 'Principal',
    'badge__verified' => 'Verificado',
    'badge__unverified' => 'Não verificado',
    'badge__default' => 'Padrão',
    'badge__you' => 'Você',
    'paginationButton__previous' => 'Anterior',
    'paginationButton__next' => 'Próximo',
    'paginationRowText__displaying' => 'Exibindo {start}-{end} de {total}',
    'paginationRowText__of' => 'de',
];
