<?php

declare(strict_types=1);

namespace App\Auth\Saml;

use App\Models\EnterpriseConnection;
use App\Support\Url;
use DateTimeImmutable;
use LightSaml\Credential\KeyHelper;
use LightSaml\Helper;
use LightSaml\Model\Assertion\Assertion;
use LightSaml\Model\Assertion\Issuer;
use LightSaml\Model\Assertion\NameID;
use LightSaml\Model\Context\DeserializationContext;
use LightSaml\Model\Context\SerializationContext;
use LightSaml\Model\Metadata\AssertionConsumerService;
use LightSaml\Model\Metadata\EntityDescriptor;
use LightSaml\Model\Metadata\KeyDescriptor;
use LightSaml\Model\Metadata\SpSsoDescriptor;
use LightSaml\Model\Protocol\AuthnRequest;
use LightSaml\Model\Protocol\Response as SamlResponse;
use LightSaml\Model\XmlDSig\SignatureXmlReader;
use LightSaml\SamlConstants;

/**
 * SAML 2.0 engine wrapping the lightsaml library. Three public operations:
 *
 *   - `buildSpMetadata`        — emits SP metadata XML the IdP imports.
 *   - `buildAuthnRequest`      — builds a base64-encoded AuthnRequest the SDK
 *                                 redirects the user-agent to.
 *   - `parseSamlResponse`      — verifies an inbound SAMLResponse against
 *                                 `EnterpriseConnection.saml_idp_certificate`,
 *                                 audience, recipient and expiry; returns a
 *                                 `SamlAssertion` value object.
 *
 * The encrypted SP signing key on `EnterpriseConnection.saml_signing_key`
 * is generated by the BAPI/FAPI create endpoint (AU-5/AU-6); this service
 * is read-only with respect to that material.
 */
final class SamlConnectionService
{
    /**
     * Builds the SP-side metadata XML. The IdP admin imports this to know
     * where to POST the SAMLResponse (`saml_acs_url`) and what SP entity
     * id to expect in `Audience`.
     */
    public function buildSpMetadata(EnterpriseConnection $conn): string
    {
        $entityDescriptor = new EntityDescriptor;
        $entityDescriptor->setEntityID($this->spEntityId($conn));

        $sp = new SpSsoDescriptor;
        $sp->setProtocolSupportEnumeration(SamlConstants::PROTOCOL_SAML2);
        $sp->setWantAssertionsSigned(true);

        $acs = new AssertionConsumerService;
        $acs->setBinding(SamlConstants::BINDING_SAML2_HTTP_POST);
        $acs->setLocation($this->acsUrl($conn));
        $acs->setIndex(0);
        $sp->addAssertionConsumerService($acs);

        if (is_string($conn->saml_signing_key) && $conn->saml_signing_key !== '') {
            $signingX509 = $this->extractCertificateFromKeyPair($conn->saml_signing_key);
            if ($signingX509 !== null) {
                $keyDescriptor = (new KeyDescriptor)
                    ->setUse(KeyDescriptor::USE_SIGNING)
                    ->setCertificate(KeyHelper::createPublicFromKeyData($signingX509));
                $sp->addKeyDescriptor($keyDescriptor);
            }
        }

        $entityDescriptor->addItem($sp);

        $context = new SerializationContext;
        $entityDescriptor->serialize($context->getDocument(), $context);

        return (string) $context->getDocument()->saveXML();
    }

    /**
     * Build a base64-encoded AuthnRequest the SDK redirects the user-agent
     * to. `$relayState` survives the IdP round-trip and lets the ACS handler
     * (AU-7) bind the inbound assertion back to the right SignIn / SignUp.
     */
    public function buildAuthnRequest(EnterpriseConnection $conn, string $relayState): string
    {
        $request = new AuthnRequest;
        $request
            ->setID(Helper::generateID())
            ->setIssueInstant(new \DateTime('now', new \DateTimeZone('UTC')))
            ->setDestination((string) $conn->saml_sso_url)
            ->setProtocolBinding(SamlConstants::BINDING_SAML2_HTTP_POST)
            ->setAssertionConsumerServiceURL($this->acsUrl($conn))
            ->setIssuer((new Issuer)->setValue($this->spEntityId($conn)));

        $context = new SerializationContext;
        $request->serialize($context->getDocument(), $context);
        $xml = (string) $context->getDocument()->saveXML();

        return base64_encode($xml);
    }

    /**
     * Verify and unwrap an inbound SAMLResponse. The full ceremony:
     *  1. Base64-decode + parse the response into a `Response` model.
     *  2. Verify the embedded XML signature against `saml_idp_certificate`.
     *  3. Confirm `Audience` matches our SP entity id.
     *  4. Confirm `NotOnOrAfter` has not elapsed (60s clock-skew tolerance).
     *  5. Extract the assertion's NameID + AttributeStatement + AuthnContext.
     *
     * Throws `SamlException` on any verification failure.
     */
    public function parseSamlResponse(string $samlResponseB64, EnterpriseConnection $conn): SamlAssertion
    {
        $xml = base64_decode($samlResponseB64, true);
        if ($xml === false || $xml === '') {
            throw new SamlException(SamlException::REASON_MALFORMED, 'SAMLResponse is not valid base64.');
        }

        $deserialization = new DeserializationContext;
        $deserialization->getDocument()->loadXML($xml);
        $response = new SamlResponse;
        $response->deserialize($deserialization->getDocument()->documentElement, $deserialization);

        $assertions = $response->getAllAssertions();
        if ($assertions === []) {
            throw new SamlException(SamlException::REASON_MALFORMED, 'SAMLResponse carries no assertion.');
        }
        $assertion = $assertions[0];

        $this->verifySignature($response, $assertion, $conn);
        $this->verifyAudience($assertion, $conn);
        $notOnOrAfter = $this->verifyExpiry($assertion);

        $nameIdModel = $assertion->getSubject()?->getNameID();
        if ($nameIdModel === null || $nameIdModel->getValue() === null) {
            throw new SamlException(SamlException::REASON_MALFORMED, 'Assertion has no NameID.');
        }

        return new SamlAssertion(
            nameId: (string) $nameIdModel->getValue(),
            nameIdFormat: $nameIdModel->getFormat(),
            attributes: $this->collectAttributes($assertion),
            sessionIndex: $assertion->getFirstAuthnStatement()?->getSessionIndex(),
            notOnOrAfter: $notOnOrAfter,
            authnInstant: $this->dt($assertion->getFirstAuthnStatement()?->getAuthnInstantTimestamp()),
            authnContextClassRef: $assertion->getFirstAuthnStatement()?->getAuthnContext()?->getAuthnContextClassRef(),
        );
    }

    public function spEntityId(EnterpriseConnection $conn): string
    {
        return Url::fapi($conn->environment, '/saml/'.$conn->id);
    }

    public function acsUrl(EnterpriseConnection $conn): string
    {
        return Url::fapi($conn->environment, '/v1/saml/'.$conn->id.'/acs');
    }

    private function verifySignature(SamlResponse $response, Assertion $assertion, EnterpriseConnection $conn): void
    {
        $signature = $assertion->getSignature() ?? $response->getSignature();
        if (! $signature instanceof SignatureXmlReader) {
            throw new SamlException(SamlException::REASON_SIGNATURE, 'Assertion is not signed.');
        }
        if (! is_string($conn->saml_idp_certificate) || $conn->saml_idp_certificate === '') {
            throw new SamlException(SamlException::REASON_SIGNATURE, 'Connection has no IdP certificate to verify against.');
        }
        try {
            $certificate = KeyHelper::createPublicFromKeyData($conn->saml_idp_certificate);
            $valid = $signature->validate($certificate);
        } catch (\Throwable $e) {
            throw new SamlException(SamlException::REASON_SIGNATURE, $e->getMessage());
        }
        if (! $valid) {
            throw new SamlException(SamlException::REASON_SIGNATURE, 'Signature did not verify against the connection certificate.');
        }
    }

    private function verifyAudience(Assertion $assertion, EnterpriseConnection $conn): void
    {
        $expected = $this->spEntityId($conn);
        foreach ($assertion->getAllAudienceRestrictions() as $restriction) {
            foreach ($restriction->getAllAudience() as $audience) {
                if ($audience === $expected) {
                    return;
                }
            }
        }
        throw new SamlException(SamlException::REASON_AUDIENCE, "No AudienceRestriction matches {$expected}.");
    }

    private function verifyExpiry(Assertion $assertion): ?DateTimeImmutable
    {
        $latest = null;
        $tolerance = 60; // seconds — clock-skew slack
        foreach ($assertion->getAllSubjectConfirmations() as $confirmation) {
            $notOnOrAfter = $confirmation->getSubjectConfirmationData()?->getNotOnOrAfterTimestamp();
            if ($notOnOrAfter === null) {
                continue;
            }
            $latest = $notOnOrAfter;
            if ($notOnOrAfter + $tolerance < time()) {
                throw new SamlException(SamlException::REASON_EXPIRED, 'SubjectConfirmation NotOnOrAfter has elapsed.');
            }
        }

        return $this->dt($latest);
    }

    /**
     * @return array<string, list<string>>
     */
    private function collectAttributes(Assertion $assertion): array
    {
        $out = [];
        foreach ($assertion->getAllAttributeStatements() as $statement) {
            foreach ($statement->getAllAttributes() as $attribute) {
                $name = (string) $attribute->getName();
                $out[$name] ??= [];
                foreach ($attribute->getAllAttributeValues() as $value) {
                    $out[$name][] = (string) $value;
                }
            }
        }

        return $out;
    }

    private function dt(?int $timestamp): ?DateTimeImmutable
    {
        if ($timestamp === null) {
            return null;
        }

        return (new DateTimeImmutable)->setTimestamp($timestamp);
    }

    /**
     * Accept either a PEM-formatted certificate alone, or a key-pair PEM
     * containing the certificate first. Returns the PEM-formatted certificate
     * (with header/footer) or null if none is found.
     */
    private function extractCertificateFromKeyPair(string $pem): ?string
    {
        if (preg_match('/-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----/s', $pem, $match)) {
            return $match[0];
        }

        return null;
    }
}
